################################################################################
#!perl -w
#
#  SqlSourceNumber - Reset any SourceNumbers back to Lightspeed values
#
################################################################################



# Pragmas
use strict;
use Getopt::Long;
use Cwd;



use Content::File;
use Content::SQL;



my $opt_help;
my $opt_version;
my $opt_debug;
my $opt_wizard;					# True if I should't display headers and footers
my $opt_table;					# The table name if transfering only a single table


my @domain_list = qw (
us.eoeuro
us.qpoeruel4
us.paperboard
us.dpfouiqo5
us.poqeoiru6
us.ybmean
us.misbilling
us.ispx
us.yachtman
us.saryu
us.district9
us.vergeer
us.net-salez
us.yarboro
us.navigates
us.victoriacorner
us.aa0ru08
us.narrowly
us.valleyriver
us.foldentownship
us.ns-quatro
us.bronchoscopist
us.bestratesnow
us.tonnish
us.111ouroue
us.lungers
us.mn
us.nodulation
us.gamic
us.tx
us.onlinehome
us.eorue
us.legalley2
us.unhopeful
us.nordhoff
us.littlenarrowsu
us.ns-dois
us.gristliestu
us.orthoepy
us.ajldfj
us.gastroscopist
us.garget
us.scud3765biz
us.1owinterest
us.in
us.venae
us.intensifier
us.evorav
us.swityex
us.avoids
us.outpoll
us.misposition
us.ofalx
us.infiltrator
us.triplicities
us.flatau
us.ia
us.interrow
us.oh
us.philothea
us.il
us.mysupercd
us.supercdonline
us.whipstitching
us.headships
us.fl
us.hyoid
us.ingoing
us.nc
us.delver
us.thawing
us.oper22
us.mi
us.fanon
us.donnellycity
us.quartermasters
us.wa
us.wi
us.ny
us.lifesaver5subitem
us.isopach
us.icecreamz
us.want-it-now
us.nesip
us.111orueor
us.tuuyo1
us.bluebare
us.langostino
us.ma
us.hfgr33
us.powty
us.mirit
us.ar
us.tradeoff2pastiches
us.rhizopi
us.1ead2u
us.va
us.sharona
us.nowyouseeit
us.immunityx
us.supercd
us.armorial1474biz
us.igf2
us.star1eads
us.pa
us.or
us.rapporteur3slanderous
us.overloaded2313biz
us.nonmainstream
us.suncdsite
us.maximization
us.eoreoru
us.metabolic2smelly
us.ms
us.co
us.ky
us.ne
us.trespassing
us.nelsonhollow
us.querela1822meds
us.plenum2roulette
us.bb30480
us.mcbrien
us.unsaddle8sagacious
us.aa034u3
us.referral9466pill
us.esis
us.nj
us.shrieking3773pi11s
us.athanasiou
us.bb03480
us.grouch
us.md
us.k12ca
us.bb03803
us.quarterbackedt
us.auger1103pills
us.mo
us.superhero2yeasts
us.syllabify4062drug
us.katzner3273biz
us.mtgdefault
us.voladorasbarrio
us.kamilliap
us.nappierv
us.smallest9092drug
us.aruizu
us.tn
us.usefully6308rx
us.nicklow
us.zchildscreek
us.nortriptylinew
us.virginia-sites
us.id
us.conducers
us.nh
us.hebetic
us.az
us.zdistrict1fork
us.ruin6998rx
us.psycho7294drugs
us.obliterating
us.ok
us.me
us.hric1
us.victimize4839pill
us.sanguinely3104drug
us.kwh2116meds
us.ga
us.laxative5682dryg
us.al
us.11dot
us.schemers4096pi11s
us.triteness8504drug
us.akimbo6968tabs
us.handcraftsmen
us.canalizations
us.wordless1461tabs
us.tentative1876tabs
us.permian3231tabs
us.dlfjljdd2
us.cornstalk8555pill
us.meru
us.bbouroe
us.hakepe
us.aspirated8343pi11
us.stilton4040drugs
us.cardboard6611biz
us.gatliff
us.lubric
us.ct
us.la
us.ks
us.max-online
us.getup7
us.inflect5194drygs
us.rejoice1125rx
us.htm
us.comclientca-dp-momentousxmldomainnameyoga
us.largely8979drygs
us.jesuitic
us.efouiof
us.wv
us.sprang3978pill
us.ait4453pill
us.outplay986biz
us.rates4unow
us.ekhauv
us.bbldfj
us.lookingat
us.jiffy4
us.ut
us.slaphappy7346meds
us.sheik1028meds
us.simian4offeree
us.bbeoru
us.gaped
us.polished8soundly
us.111odfueo
us.dislocated9298pills
us.nude7755pi11s
us.scrapbook3383meds
us.fieldstrip
us.outlined189tabs
us.rx4usandu
us.immortelle9
us.immature4319pills
us.bales5994meds
us.bbeorue
us.111arueor
us.pensive1701drugs
us.department5215rx
us.nut4999biz
us.buttermilk
us.kehape
us.torpid1103biz
us.boiler6872pill
us.patellas2315pill
us.seraglios121pill
us.surrealistic
us.defaultmtg
us.penumbral7470drugs
us.oppress1170tabs
us.pollinator6632tabs
us.ingulfed
us.sundae8155pi11
us.headmen
us.wy
us.hopefully3701rneds
us.striptease9199pill
us.sprig4006rx
us.sanyu
us.111oueroeu
us.sc
us.skydives9635pi11s
us.journalistic
us.pickpocket2persevered
us.vt
us.gsmportal
us.caraway307biz
us.duke7154tabs
us.sees3fungi
us.dtownshipno3
us.eiptpeu
us.nm
us.fervently9835drugs
us.vital7482drugs
us.111aureoru
us.doxie3
us.countess8253tads
us.stiles8440rneds
us.aa08340
us.lidov
us.comclientca-dp-momentousxmldomainnamechinatown
us.propylene3479pi11s
us.111adfuod
us.aopdufo
us.ghelh88
us.risk-free
us.best8938rx
us.unordered6621rx
us.sanction6029biz
us.221dvd
us.weeds2181biz
us.smscentrum
us.tibial5decadent
us.duodenum6414biz
us.111odfuod
us.involute6538drygs
us.diatribe3927pill
us.comclientca-dp-momentousxmldomainnamedalzell
us.marl
us.zinger4102drug
us.indoctrinated
us.aa03843
us.qwer
us.reel2598rx
us.aiuf3uer1
us.tubes5064pills
us.596
us.comm
us.outgoing9256pi11s
us.weblogs
us.redrawing5984biz
us.zase
us.comclientca-dp-momentousxmldomainnamewills
us.netlogo
us.leaked6805drugs
us.abjurer6060drugs
us.defeat6518drug
us.remake9252tabs
us.irin
us.598
us.designate7919drug
us.dahlhauser7
us.coml
us.mt
us.permanent2811tabs
us.comclientca-dp-momentousxmldomainnameonce
us.meerschaum7612pi11
us.ggoo
us.aghous
us.aaoeuro
us.comclientca-dp-momentousxmldomainnamebus
us.deepened4521tabs
us.presbyter7381drugs
us.stapedes3075drug
us.manhole4962biz
us.patronizer6687tads
us.gaininches
us.vamoslamoveon
us.flimsiness4164dryg
us.novelettish
us.unbeatable681rx
us.enough1698drugs
us.frankit
us.mtgdflt
us.sociologic3084biz
us.yapped2284pills
us.smock928pill
us.aghtus
us.comclientca-dp-momentousxmldomainnamecart
us.awse
us.leaden9828biz
us.qwar
us.haan2
us.afdla
us.insecure7285tabs
us.pyramidic3057biz
us.dtownshipno7
us.bradstreet3262pill
us.comclientca-dp-momentousxmldomainnametango
us.sweated1427pi11
us.copier4859rx
us.bodily1529rneds
us.sideband9064dryg
us.search-55
us.bdlfu
us.durdenitejn
us.ak
us.aghoyoe
us.hard8589meds
us.suncdonline
us.esiddiq
us.papasite
us.subpoenas2114drug
us.startling707biz
us.comclientca-dp-momentousxmldomainnamewilcox
us.fateful3948pill
us.outcrow
us.vegs
us.fontal9137biz
us.aghoesss
us.craigz
us.aa08309
us.genius5748pills
us.odessa2602drug
us.resentful9803drugs
us.diddle1819meds
us.wimbledon743pill
us.vom
us.altdot
us.jannel
us.lojdfpqo
us.auspicious1886drug
us.nv
us.dorty7
us.misentry1982rx
us.cricket6735drugs
us.backhoe613drug
us.comclientca-dp-momentousxmldomainnameroadhouse
us.comclientca-dp-momentousxmldomainnamemodel
us.matchless3341rx
us.ate6640drugs
us.complexity1006pill
us.idiotic
us.dou33
us.societal1329biz
us.defrayal6summoned
us.dkldhfg33
us.hortu
us.k12il
us.imaum
us.zarf1antipodean
us.thesupercd
us.597
us.prelim7911meds
us.cmo
us.songsfrom
us.mortgaged7436biz
us.odel
us.daltonic805drygs
us.contriteness
us.breakup9732pi11
us.megacunt1810rx
us.burguie
us.594
us.dukedom221meds
us.tsar6havana
us.somnolence843rneds
us.massachusetts-sites
us.sabbaths396pill
us.111aueroeu
us.ammmsor
us.mortgagequest
us.closed6129tads
us.vegus
us.belligerent
us.specials4u
us.slowpokes4043pill
us.smeltery7284pills
us.armoured6658pill
us.honeyed7326biz
us.e2busy
us.webdir
us.abjuration2appaloosa
us.about-blank
us.sceptical5237tabs
us.salezfirm
us.snowballed8493drugs
us.espoieu
us.barmaid1641drug
us.carp6499pi11s
us.espoeiur
us.comclientca-dp-momentousxmldomainnameteam
us.stye3546drugs
us.centralism3766rx
us.assumpsit9521drygs
us.strictness2700pills
us.immense5235drygs
us.unicity805tabs
us.cachinnations
us.twisted5480drygs
us.111dlfj
us.packsite
us.sd
us.hi
us.kepeha
us.ldjf
us.killing8335biz
us.arboricultural
us.suncd
us.loupqoeu
us.statutory1625pi11s
us.seasoning6949drug
us.practicing8297tabs
us.foodstuff
us.de
us.okapi9976drugs
us.som
us.hopasz
us.stomp9963rx
us.rhubarb454rneds
us.cog5687tads
us.labeb
us.halberd6848pill
us.taurus4232drug
us.045
us.globe4904pills
us.tiered8070pi11
us.enactment859drygs
us.dialect752meds
us.aiuf3uer3
us.childish5admen
us.wisdom8pcb
us.aadofuo
us.statez
us.bean2ambivert
us.approvalrates
us.garotte
us.rami8allelic
us.shipshape6075pi11
us.narrowly9558pi11
us.apologies4018tabs
us.skydance5355pi11
us.giarraputo
us.backward6376rx
us.united9broken
us.pompadour8149meds
us.fugacious2107pill
us.workman3166tabs
us.bpcdn
us.aelefa
us.sharewith
us.teenage5800meds
us.trinity7698pi11s
us.promote9796drug
us.living9448pill
us.quixote2572rx
us.delude1439pill
us.disapproving
us.judge9776biz
us.clm
us.quadrilliontht
us.thehomeofrx
us.ri
us.abnegation9784rx
us.ceto
us.nsn
us.mysuncd
us.democrat8481rx
us.smocked5251pill
us.poncho4491dryg
us.cancelations
us.whatarate
us.salomansize
us.luxuriate7999tads
us.lingo376pill
us.eachicem
us.eachicek
us.daceohad
us.zhatglow
us.rateitin
us.ratetine
us.hagldado
us.neoncarot5
us.aallywin
us.birdasin
us.damsohep
us.ayouacid
us.daffhajk
us.boldness9resist
us.sunglow51
us.aareark
us.aairswoe
us.baghdad2145drugs
us.daceihad
us.dameqhem
us.zflubyte
us.heppdams
us.nredoak2n
us.grnyellow4
us.zhetbrow
us.haddacen
us.pietlate
us.pielatev
us.iceeachj
us.smacked8425rx
us.aareawax
us.pielatex
us.dacemhad
us.bedtime7591rx
us.felonious2546tabs
us.hadqdace
us.aahhcarm
us.dagohaom
us.biteshyo
us.043
us.hempdame
us.pielatec
us.california-info
us.damskhep
us.iceeachp
us.zfencrib
us.bedcrowt
us.nd
us.dacehadi
us.zhetbrim
us.bitcallc
us.agagbach
us.actsoyes
us.dadoqhag
us.haddacej
us.zfencaph
us.jpg
us.spruce2
us.arteriole1448drygs
us.aazanzoo
us.beatotea
us.turquoise14
us.bendsoyi
us.trumpttree
us.ultragreen2
us.eachicer
us.nvyblue62
us.aarchway
us.boasbfee
us.daffhajr
us.hagndado
us.damshepm
us.hemdamen
us.icejeach
us.okamechry2t
us.ncatalpa2m
us.dagohaoi
us.111auroue
us.zimmermancityk
us.blurekez
us.zgagbach
us.097
us.nonblank4701biz
us.damshepk
us.bellspyo
us.hagdadoj
us.tupelox4
us.rateatin
us.bitcallz
us.k12va
us.browhets
us.eachkice
us.shemaleclub
us.mingfern
us.eachmice
us.aantrama
us.daffhajm
us.qdigirto
us.daceqhad
us.daffhajo
us.aahemwow
us.jhepdams
us.bitcallv
us.dadomhag
us.hasdahlr
us.hehqdaks
us.iceeachn
us.hepqdams
us.mulberry65
us.bitsisew
us.aahvbitt
us.hepdamsl
us.eachoice
us.mgcdn
us.bedcrowv
us.alfaawit
us.rateetin
us.callbbit
us.bluewhale5
us.azagaces
us.tulip4r
us.iceeachr
us.hagdadon
us.dameihem
us.mimosa2k
us.skills4744rneds
us.aahbittz
us.daffmhaj
us.eachicei
us.ajariwiz
us.dacehadk
us.aaimswok
us.moths3
us.natalplum
us.bedxcrow
us.sourgum8
us.zincrant
us.datwansa
us.bitcallt
us.ultrared790
us.ieachice
us.phonograph8816rx
us.dadohagm
us.amended1196pill
us.dicjz
us.aa98347
us.bittcall
us.beesosum
us.trimly8932tabs
us.cribyfen
us.zfeeboas
us.damehemo
us.bentsoxo
us.hadldace
us.toenail1911pi11
us.zhepcubs
us.aacdn
us.nuttail2p
us.dacehado
us.aairaim
us.ultra82orng
us.ultra14yelo
us.betsskyi
us.busheggb
us.ratetinc
us.agues346rneds
us.bussjobu
us.ringlet6664biz
us.daffkhaj
us.sunlocust2
us.dacehadm
us.damshepo
us.viletprple
us.tuberous4736meds
us.waterside9155dryg
us.bitssewi
us.overblown4476pi11s
us.348
us.bedcrowc
us.aosotue
us.blurekeu
us.dagomhao
us.beltspaa
us.aagewade
us.afencaph
us.thistle96
us.aailnair
us.dagohaok
us.jiceeach
us.hepdamsp
us.ayesacts
us.stackers1647biz
us.zgobcage
us.bellospy
us.chafe4650tabs
us.dc
us.thickas
us.pielatet
us.haddacer
us.hemdamej
us.kdaksheh
us.fitch7826drug
us.ahoywooo
us.hagdador
us.plumber6307drygs
us.hepndams
us.hepdamsr
us.hemdamer
us.yogi853biz
us.aleacusp
us.hepjdams
us.bookdelb
us.damehemk
us.cribwfen
us.bimawcog
us.dagohaoo
us.ahetbrow
us.k12wi
us.rateting
us.dacehadr
us.beersuni
us.aahxbitt
us.hemldame
us.weak2133drug
us.bussjobz
us.herbalmagic
us.hadpdace
us.bilvdate
us.begsisub
us.blueviolt1
us.gob
us.arubunse
us.afunfur
us.lhepdams
us.shybitei
us.iceqeach
us.blatepie
us.hepldams
us.lettersfrom
us.daffohaj
us.dacekhad
us.dagoihao
us.calesand
us.ailtnair
us.ultra5pink
us.afencrib
us.hemndame
us.betsisky
us.afidsdia
us.bushyegg
us.commusao
us.bimacogb
us.lemonyell5
us.hemjdame
us.haddacep
us.ort
us.uue89
us.searim7571tads
us.arupeemf
us.ahagibud
us.aanyant
us.hepdamsn
us.espousing7883rx
us.bookdels
us.daffqhaj
us.severally9415meds
us.sweetgum5t
us.pzaftrace
us.bimaucog
us.bitcallx
us.orchid512
us.basf4388pi11
us.ultra790blue
us.aaltowho
us.dadoihag
us.crowbeds
us.haddacel
us.dahlhasm
us.ainsghia
us.aflubyte
us.oauifopu8
us.cuspleas
us.seemingly6527drygs
us.aapeswet
us.eachqice
us.unmelyel5
us.teenbest
us.canwairo
us.bedcrowx
us.odamshep
us.bathrobe5538pi11
us.afeeboas
us.hagdadol
us.digestion5594rneds
us.abetben
us.occupying
us.tearfully5strums
us.dahlohas
us.aotpems
us.bibsoski
us.autoredial3620pill
us.brimhetz
us.hemdamel
us.caclientca-dp-momentousxmldomainnamedalzell
us.dameohem
us.stunt9046pi11s
us.dadohago
us.jhehdaks
us.abyeziga
us.bitacall
us.mis6163pi11s
us.haspdahl
us.damekhem
us.aandcale
us.rdrumnap
us.aideiwon
us.markrecommends
us.racezaftj
us.1-herbal-remedy
us.walleye2556dryg
us.nspruce2o
us.junctural
us.entries5187drug
us.acmeayip
us.acrycut
us.aalfawit
us.adrugstorez
us.dadohagr
us.atouel
us.caclientca-dp-momentousxmldomainnameonce
us.browwhet
us.photosfor
us.beauatax
us.hehldaks
us.bestsoba
us.hehdaksn
us.pirmateb
us.flank4240biz
us.asapo
us.ratetina
us.1eadgal0re
us.cagebgob
us.birdsina
us.592
us.knowingly606meds
us.great-herb
us.brimhets
us.beatteao
us.damshepi
us.puoizugac
us.k12ga
us.benwaili
us.mockernu2lt
us.rategtin
us.blurekew
us.wis
us.boasfeeu
us.direct-rx
us.archwaya
us.dadohagi
us.vapine1v
us.dadohagk
us.worrisome5163pill
us.bookbdel
us.hagjdado
us.ramaanta
us.beniwail
us.sourwood4
us.beanatee
us.blurueke
us.afixflu
us.bilxdate
us.biteoshy
us.sazu
us.safekidsnow
us.ratetinj
us.portalz
us.bentosox
us.supercdsite
us.awebaqua
us.peoples-credit
us.busheggw
us.aamenwey
us.riveter5847dryg
us.hemqdame
us.pievlate
us.abackvet
us.ohiobe2s
us.candyfrom
us.furteni
us.cagegobs
us.damehemi
us.bimacogs
us.narrowly1946biz
us.aplicant6200tabs
us.alighted2110tads
us.parakeet3b
us.boasfeew
us.binewags
us.guano7904pills
us.lectriclime
us.cribufen
us.aflufix
us.bussjobs
us.beanteea
us.crowbbed
us.apowhung
us.overoak2x
us.apercus9591dryg
us.darksban
us.bildatex
us.blueaset
us.cheap-drugs
us.rbaagolf
us.ailnairc
us.bookdelw
us.bimabcog
us.bowman8103drug
us.astrolabe9495rx
us.raceuzaft
us.all-rxdrugs
us.saver9straight
us.uncolored8avaunt
us.nhepdams
us.bearited
us.k12mn
us.singl
us.qts7851drygs
us.alitalia9689pi11
us.caulds
us.benzene4347drug
us.bidsasix
us.soybenda
us.abendsoy
us.k12ny
us.awoeairs
us.fed
us.paris2standee
us.bdfljdl
us.biergulz
us.amend4555rx
us.agymhad
us.campfire8speckles
us.aantany
us.phasdahl
us.cau
us.bobcatm0
us.airaaim
us.dagohaor
us.busssjob
us.paltrily110biz
us.bitvcall
us.pfizer7972biz
us.adrugstoresz
us.axing5875pi11s
us.canowair
us.hadndace
us.peddler8scenes
us.pla89
us.gagliardotto
us.bnairail
us.browhetz
us.assemblies7268biz
us.agatgel
us.pawpaw2z
us.datawans
us.ailvnair
us.astf2571pills
us.pirhmate
us.area-homes-for-sale
us.aoutpet
us.k12ut
us.binwagse
us.darkbban
us.bimaycog
us.spending8718pill
us.beepatag
us.cuspblea
us.bushbegg
us.iceleach
us.outraorng5
us.boassfee
us.kdjfldjk
us.ynotmyrx
us.caclientca-dp-momentousxmldomainnamewills
us.ewerthebestrx
us.cas
us.bonobom0
us.icepeach
us.cadiwelf
us.shuddered4plutocracy
us.jhemdame
us.darkbanz
us.armiwaft
us.signaler306pill
us.suborning7098pills
us.caclientca-dp-momentousxmldomainnamecart
us.activedrugsco
us.beautaxa
us.textiles528tads
us.aiceill
us.dagoohao
us.quantifiable
us.werthebestrx
us.jent4
us.aahoywoo
us.caleyand
us.beetasue
us.beeptaga
us.batsotin
us.snowonmtn
us.aartswad
us.longerthan
us.sweet90
us.iusacomm
us.wrasse8984pi11
us.olympus8924biz
us.aaskash
us.jmtgk
us.aimsawok
us.farcical3545rneds
us.ainghiaf
us.bglowhat
us.caclientca-dp-momentousxmldomainnamewilcox
us.aahbittc
us.agumgun
us.allaboutdietdrugs
us.crowbedb
us.ahughue
us.jell8297drugs
us.k12ia
us.stillwater7481drug
us.cuspslea
us.stillness4372pills
us.tiptoe1538rx
us.spiffily6532biz
us.beetsuea
us.puoizugaa
us.ofinban
us.beefotan
us.niceeach
us.very9221rx
us.piealate
us.ddecsoso
us.abcdiscountdrugs
us.octred2r
us.pdf
us.uinquire
us.ahatglow
us.carf
us.com-online
us.guillotine416rx
us.webwealth
us.shingle6722dryg
us.actsyeso
us.pocketbook2rightly
us.afordabledrugs
us.flatfoot8255tabs
us.asperse6bak
us.woodwind9505tabs
us.fourfold2611pi11
us.fmconcepts
us.bindosip
us.ahetbrim
us.k12tx
us.facedown7001biz
us.austurkey7
us.sweaty8501meds
us.protocol5780pills
us.egreth8
us.bendisoy
us.unhewn2916drug
us.saddleback8141drygs
us.dagokhao
us.bildatec
us.home-mortage
us.womrc
us.aismcoop
us.bikeisit
us.syphilitic1illustrate
us.alldaydrugstore
us.kdamehem
us.matsuk12
us.boasufee
us.beerisun
us.k12mi
us.aaeorue
us.cok
us.blurbeke
us.ftpz
us.aid-ritedrugs
us.hemdamep
us.aft7772drugs
us.ahemwowa
us.042
us.svus
us.all-drugstore
us.fabricate2671rneds
us.damemhem
us.abailtye
us.cowi
us.urethral3which
us.abeetsue
us.daffihaj
us.iceneach
us.bildatet
us.aapexwed
us.zigabyeo
us.berate5731biz
us.sycamore2b
us.cous
us.ptl2464pi11
us.sixths3280rx
us.ajarwizi
us.spiralling3612tads
us.conflict8955pill
us.bedsitap
us.arooto
us.activedrugs
us.amateurfree
us.jenniffer4
us.taper1602biz
us.aidwvane
us.afbees5a
us.texassage
us.brimhetb
us.thesassy
us.k12az
us.atoelujd
us.fraudulent4567pill
us.mr-2
us.squired5230tabs
us.allfind
us.hehdaksp
us.entail2096drygs
us.aimfuiod
us.wores
us.finiban
us.actiondrugs
us.zitiabed
us.hehpdaks
us.prayingfor
us.teacupful8826drygs
us.all-prescription-drugs
us.womrr
us.eorueo
us.succotash9845rx
us.masterfasteratlarge
us.ebonni
us.dusseldorf3527pills
us.all-night-drugstore
us.sleusure
us.squirms5bird
us.gove
us.acneiyet
us.bedvcrow
us.skunk2642drugs
us.disrobe2cental
us.deu
us.xgoto
us.aa30483
us.comtx
us.storiesfrom
us.hehjdaks
us.societies7375tads
us.dagoqhao
us.k12mo
us.lacebark2d
us.steels239drygs
us.lifeminders
us.amateurish8859rx
us.stolidly8964biz
us.witoalfa
us.netclientca-dp-momentousxmldomainnametango
us.pill-pharmacy
us.eynotmyrx
us.stopover4441rneds
us.rouge8615dryg
us.airswoeo
us.womr
us.aceszagi
us.pulsar6021pi11
us.wetoapes
us.pills-rx
us.affordablerxdrugs
us.all-prescriptiondrugs
us.racezafto
us.ex-patch
us.quickset3498meds
us.bildatev
us.fox621dryg
us.swordfern
us.pluhne89
us.aahbittv
us.208dvd
us.hehdaksj
us.all-drugs-pharmacy
us.dahlihas
us.commousa
us.k12ar
us.k12nj
us.iceeachl
us.as
us.queerness4934drug
us.acalmmen
us.affordableonlinedrugs
us.maritzloyalty
us.esouroe
us.eachiice
us.ajamivy
us.pignut3b
us.dni
us.slovak9149pi11s
us.atoerul
us.bridegroom6963rx
us.bedcrowz
us.abikesit
us.polity3403drygs
us.budhagim
us.bierugul
us.aptewaes
us.qua5hmm
us.caclientca-dp-momentousxmldomainnametango
us.tantalizes6507dryg
us.statu2201pi11
us.atipbath
us.itinto
us.220dvd
us.docket9430pi11
us.ayumache
us.065
us.bidssixa
us.pirbmate
us.acancab
us.tolerate6617biz
us.bedstapi
us.abagbam
us.s
us.mobiletone
us.aptwaese
us.allaboutdrugstore
us.ajugkeg
us.oleaginous9337meds
us.ababyvex
us.budlhagi
us.bachgags
us.asoutoe
us.usacommi
us.k12fl
us.all-drugs
us.eanew
us.cin
us.mantilla7896rx
us.gh6
us.damehemm
us.beessumo
us.itsfun
us.pirdmate
us.zinacran
us.videosfrom
us.pixeslot
us.bluebarz
us.bedacrow
us.wokaimsi
us.tipped2161pills
us.defenses8093biz
us.shyxp
us.newtonian7hemorrhoid
us.mex
us.ahepcubs
us.powrpage
us.aabek89
us.fuzz3degrees
us.outcry5perjurious
us.prg
us.ukclientca-dp-momentousxmldomainnamewills
us.rating1857rneds
us.egoistic4unleavened
us.scarfs7993pi11s
us.affordablerxdrugstore
us.tex
us.brimshet
us.burying1974rx
us.adrugstores
us.housingregistry
us.ws4f
us.barraca
us.brimhetu
us.georgiar
us.prosecute3311drugs
us.brimwhet
us.kil
us.awigaloe
us.awailben
us.stereo661drugs
us.epppp
us.affordibledrugsonline
us.acheyumi
us.hehdaksl
us.biersgul
us.taster6thymus
us.bitterly5094rneds
us.shyx
us.injecting5275pi11s
us.polotuoi
us.ww4
us.bookdelz
us.submityoursitenow
us.rework5964drugs
us.sepsis1conceit
us.lhemdame
us.k12
us.hagqdado
us.toque2063pill
us.abeltspa
us.axolotls3d
us.hehdaksr
us.wizajaro
us.achievers351drygs
us.k12ky
us.zinxcran
us.intendant491pills
us.squally7845tabs
us.reasoning3420rx
us.atugbald
us.k12oh
us.cipher7630pill
us.actonrxdrugs
us.allcelebrities
us.sherrard
us.borrower6275meds
us.decatur9854rx
us.netclientca-dp-momentousxmldomainnameyoga
us.darkbanw
us.bcoopism
us.blurekes
us.111oureor
us.the-pills
us.pleasekiss
us.adultpornmovies
us.cs
us.crucify8156pi11
us.webmergeinc
us.ailanair
us.poppies2087tads
us.masterlinkisp
us.ocommusa
us.tarsal2553tabs
us.cronew
us.puddle2
us.rx-cheap
us.timolol5097nx
us.abidssix
us.dahlhaso
us.amaster
us.ywha8462drugs
us.martinique4474tabs
us.apielate
us.965
us.vir3
us.allamericandrugs
us.buses
us.punchboard5140drugs
us.pinkapple
us.corp
us.cctx
us.christoffel
us.celery
us.console
us.afordabledrugsonline
us.bluecentury
us.talkinbout
us.las-tiendas
us.scrunch5squabs
us.nubiz
us.jkmtg
us.sheldrake9641dryg
us.houselink
us.license-searches
us.ncu
us.nt5
us.plainly8346biz
us.doingitwith
us.whence9598rneds
us.anti
us.lose
us.netclientca-dp-momentousxmldomainnameroadhouse
us.silvers2867biz
us.blurseei
us.ahemawow
us.kick6502pi11
us.abunbut
us.adamsdrugs
us.sugberry0w
us.splint985tads
us.aqmarine
us.orange52
us.ill
us.stream8759dryg
us.abegssub
us.coolness6579meds
us.jumbofiddlers
us.beget
us.home-mortgage-loan-rates
us.bycity
us.flatcoat
us.cameroun
us.boam4
us.historian3723meds
us.motivatemenow
us.aabbcc
us.storefront5968pi11s
us.atonbark
us.borax
us.monosite
us.outweigh9214pills
us.colorador
us.bluex5
us.cowlick
us.painfreeworld
us.city-business
us.dehydrated8623meds
us.weyiamen
us.ziomek
us.concinnity6196pi11s
us.afdog4
us.phania89
us.acanwair
us.dadokhag
us.alicia
us.hyaena988drygs
us.scribe5719biz
us.ettllrx
us.check-relatives
us.cobol6997drug
us.sociopathy5677pi11
us.ukclientca-dp-momentousxmldomainnamecart
us.acogbima
us.lazy
us.subsidence2choir
us.aimswoka
us.condemnate
us.sneezer4693pills
us.123a2zrx
us.pixslote
us.dorothea
us.throughput9067pi11
us.eoeureo
us.shied5615rneds
us.vioxoom
us.snow-balls
us.xtop
us.chairmen
us.pal
us.apunoil
us.wizaajar
us.amperage
us.bonn
us.collegiate5202biz
us.aabyezig
us.beartedi
us.auckland
us.contradict
us.anothercar
us.at
us.tangential3858pill
us.blueseta
us.grin7749pi11
us.allnaturalworld
us.18wow
us.topes5apparatus
us.patterson
us.abolition
us.cfm
us.din
us.kkllbbrx
us.cantonese
us.antenna
us.curriculum
us.florida-4
us.bin
us.infoclientca-dp-momentousxmldomainnamedalzell
us.bathitip
us.coot
us.gotit
us.womrrc
us.viktor3615pill
us.premium-rates
us.retyping8911rneds
us.vca
us.carol
us.drwellness
us.eoruep
us.bucket3272rx
us.sods4562rx
us.congregate
us.stephanie
us.hawaiie
us.californiar
us.doorbell
us.screams687pill
us.hagpdado
us.asparagus
us.brambling7348tabs
us.acculturate
us.bibb
us.tollfreeusa
us.ringsignaler-se
us.goc
us.cession8070drug
us.sydney
us.run-a-license-plate
us.corundum
us.simon
us.blot
us.sophia9exemptible
us.outhouse8819tabs
us.drank
us.auger
us.streetcar
us.cadaverous
us.commonplace
us.alaxcalo
us.dissonance6532pi11
us.brewster
us.hhssrx
us.footsanitizer
us.netclientca-dp-momentousxmldomainnamecart
us.kathy8786pi11
us.copperhead
us.hoop5gronked
us.bridgeinc
us.boxtwo
us.sedative1848drug
us.tactic2sombreros
us.bomb
us.mydrugsforlessrx
us.bawdy
us.alterman
us.fanstrawgold
us.es
us.speckling9172tabs
us.decked6224drug
us.cva
us.aaron
us.atkins
us.cyrconium8981biz
us.detat
us.k12co
us.home-mortgage-loans
us.amiss1573biz
us.debbie
us.essentialmedia
us.connecticutr
us.arbutus
us.arkansasr
us.cushyfoam
us.bunsen
us.sequin
us.oli
us.eur0-hydro
us.viagrabuy
us.unseen1trumpet
us.ahungpow
us.eledlfj
us.angel
us.209dvd
us.anadromous3344pi11s
us.biological-parents-search
us.clone
us.brood4cyrconium
us.superdom
us.111odufod
us.sleekly3612pi11
us.netclientca-dp-momentousxmldomainnamebus
us.mantel7435pi11
us.puoiqzuga
us.honeysuckl17
us.bristle
us.caw5709biz
us.erastus
us.odaksheh
us.bobbin
us.allcheapdrugs
us.qileicor
us.boeotia
us.murmur3unboiled
us.463
us.contagious
us.infoclientca-dp-momentousxmldomainnamewilcox
us.ukclientca-dp-momentousxmldomainnameonce
us.sunmaple1
us.wireman
us.adhesive
us.keachice
us.baugsoso
us.untalented9987drugs
us.lastminute
us.insightful
us.furrier550rneds
us.troop5258pills
us.infoclientca-dp-momentousxmldomainnametango
us.inc
us.067
us.netclientca-dp-momentousxmldomainnamewilcox
us.burrow
us.arise
us.alvarez
us.bandit
us.bijective
us.savonarola
us.afforest
us.crusade
us.disinfect7268rneds
us.sacred9295rx
us.ekkllbbrx
us.ebabe
us.agouti
us.was-u-1
us.pharmacy4u
us.operu
us.tanbark4132tads
us.custody
us.approximant
us.ukclientca-dp-momentousxmldomainnametango
us.acid
us.slouch
us.smithies7780biz
us.caddis
us.pielatez
us.cheshire
us.swf
us.director
us.afclawfrog1
us.abedbay
us.antacid
us.aplusrxworld
us.anion
us.militarist
us.shallot3840pi11s
us.affair1092drugs
us.receive5709tads
us.barren
us.motorola
us.laserlemn5
us.dadoohag
us.drain
us.nonworking1408tads
us.free-criminal-background
us.aabedzit
us.codfish
us.bbs
us.chariot
us.kalmuk
us.ancestral
us.olive306rx
us.leadeth
us.simplesuccess
us.chigger
us.stringency5048rx
us.broadway
us.bemuse
us.netclientca-dp-momentousxmldomainnamemodel
us.anamorphic
us.cinema
us.dress
us.decertify
us.document
us.com-7
us.minirav
us.hacienda
us.malabar
us.ectomorphicq
us.celesta
us.bonnie
us.insensitive
us.infoclientca-dp-momentousxmldomainnamewills
us.clamber
us.wash
us.freshman
us.oreoe
us.compellable
us.find-unlisted-cell-phone-numbers
us.alifequote4u
us.diffusible
us.diction
us.earl
us.bitumen
us.abridge
us.penrose
us.avalanche
us.abalone
us.accompaniment
us.web-site-ranking
us.ping-time
us.ore
us.areaofmusic
us.nldc
us.escapade
us.amencalm
us.efficacious
us.realinks
us.smisk
us.dachshund
us.statemn
us.coquina
us.snow2711biz
us.campground
us.affirmation
us.burnside
us.baneful
us.faber
us.smartpipe
us.caldera
us.optoacoustic
us.pirfmate
us.alp
us.triplett
us.abedozit
us.bald
us.cowpoke
us.cortland
us.bachelor
us.bona
us.doorman
us.msnbox
us.aquila
us.yacht
us.coco
us.thayne
us.delilah
us.debby
us.clang
us.downtown
us.breeze
us.lucrative
us.university-of-phoenix
us.chagrin
us.corps
us.cupboard
us.zloty
us.carburetor
us.cheapphentermine
us.auclientca-dp-momentousxmldomainnamedalzell
us.drub
us.lightupquotes
us.adirondack
us.abrasive
us.cacao
us.crockett
us.papapage
us.satisfaction
us.w3site
us.goldstein
us.gallicism2795biz
us.violetblue9
us.shod
us.privity2837dryg
us.dunbar
us.dallasa
us.assign
us.checkout
us.sux2b
us.brushfire
us.brainchild
us.misled
us.abridgment
us.doodle
us.arcane
us.florida-2
us.tangerine
us.new4urx
us.abrasion
us.tehran
us.tribe3712meds
us.mollusk
us.fuq
us.disgruntle
us.multiplex
us.babaca
us.paternoster
us.sacrificial
us.soup
us.booklet
us.bowie
us.ointment
us.culprit
us.berlioz
us.betsey
us.bishop
us.bachgagb
us.slide6037drygs
us.my
us.k12md
us.began5884rneds
us.cashgroup
us.polluting8933tabs
us.cc
us.buckley
us.thurman
us.brother
us.childbirth
us.boom
us.dahlkhas
us.baseboard
us.barshobz
us.schmidt
us.carnival
us.feminine2966biz
us.toiletstall
us.crack
us.nondescript
us.charles
us.betony
us.coale
us.aom
us.abrupt
us.hate
us.allah
us.tight
us.bizclientca-dp-momentousxmldomainnamewilcox
us.dyspeptic
us.2-page
us.boydston
us.purpledaisy
us.state
us.drunk
us.daffhaji
us.couple
us.tate
us.mega-quotes
us.befall
us.advisee
us.fasterpipelink
us.chiffon
us.bolivar
us.chorale
us.divertidas
us.ductile
us.bridal
us.nu-designs
us.ailanthus
us.guffaw
us.interlakes
us.dilate
us.disciplinary
us.colloquial
us.senses3444tabs
us.aliquot
us.solute
us.straw
us.nellie
us.donate
us.curium
us.agooddrugstore
us.cattlemen
us.phosgene
us.poncho7279rneds
us.video
us.collimate
us.preliminary
us.glamjam
us.recognizer3arg
us.premium
us.k-ent5
us.edna
us.committal
us.jading
us.cost
us.approach
us.abolish
us.people-seach
us.trace-person
us.afire
us.birthplace
us.nailedshed
us.wale
us.blurisee
us.mcclain
us.fettle
us.boa
us.cryptanalyst
us.clothier
us.tolerate
us.fiesta
us.poltuoia
us.gametek
us.worldof
us.netclientca-dp-momentousxmldomainnameteam
us.crosswort
us.lunchstraws
us.workspace
us.dogfish
us.auxiliary
us.blueberry
us.commendation
us.instalment
us.deliquesce
us.congenital
us.caricature
us.admiral
us.sourceformeds
us.apecapec
us.callous
us.wastewater
us.du
us.egan
us.verve
us.okay
us.toque3663biz
us.brigantine
us.abater
us.deluge4202drugs
us.airy
us.bertrand
us.morgue3473biz
us.danubian
us.cooperate
us.lukemia
us.jkrate
us.advisable
us.douse
us.yoga
us.mydrugsforyou
us.brainwash
us.arching
us.reservationz
us.6dollaraise
us.conqueror
us.atom
us.democratic9spright
us.stoppage9046drugs
us.erich
us.coefficient
us.esurgery
us.charlottesville
us.locate-a-lost-person
us.ayetacne
us.emanate
us.statepa
us.bongo
us.self
us.confederate
us.capacity
us.diet2
us.baby-online
us.wearisome
us.stearate
us.biochemic
us.impracticable
us.a
us.delicate
us.ldjfoue
us.acheiyum
us.was
us.debater
us.stressful
us.radiochemistry
us.cantilever
us.us
us.dec
us.jpeg
us.fangear
us.puny
us.clausius
us.ysexogratis
us.slp
us.abildate
us.dante
us.aloof
us.bucharest
us.afloat
us.nevertheless
us.bryophyta
us.736
us.orc
us.hepdamsj
us.vertebral
us.netclientca-dp-momentousxmldomainnamedalzell
us.yourself
us.barefaced
us.jewell
us.semiprune8577meds
us.governance
us.twx
us.ywca
us.blabmote
us.bushel
us.anthracite
us.adultsites
us.chromatography
us.kith
us.bookie
us.cpm
us.snowshoe
us.aimairi
us.tjc
us.e123a2zrx
us.coors
us.poulsbo
us.cowpony
us.diplomat
us.bespectacled
us.elucidate
us.extracheddar
us.linkage
us.sin324pill
us.future-savings
us.infoclientca-dp-momentousxmldomainnameonce
us.circumstance
us.chatham
us.music-sites
us.sian
us.rhodes
us.dollop
us.cheer
us.wigaloea
us.bronchial
us.alcmena
us.collapse
us.bashaw
us.bridegroom
us.ebony
us.aarhus
us.access
us.greatnet
us.delawarer
us.be-ambitio
us.cigar
us.bugle
us.a1insurancequotes
us.aphelion
us.diacritic
us.snout
us.analyst
us.blog
us.statewide
us.despond
us.calvert
us.streak
us.ulo
us.habeas
us.phthalate
us.stipend
us.covary
us.lifeappeal
us.thrombosis
us.soldiered3264tads
us.bridle
us.allaboutdrugs
us.contract
us.decksbetter
us.theasylum
us.rarefy
us.busy
us.haifa
us.censorial
us.slingshot
us.wore
us.aimsfuio
us.orange24
us.usd
us.assessor
us.abut
us.bettercastle
us.ussurveys
us.dahlhask
us.grater
us.alder
us.continua
us.leaf
us.devour
us.butzi
us.corollary
us.decomposable
us.cleancleancredit
us.healtheffects
us.advancemagazine
us.tarzan
us.treating849rx
us.keep
us.uptight4891drugs
us.niacin
us.philip-baseball
us.dahlmhas
us.cape
us.k12wv
us.laugh1505meds
us.bartlett
us.beefsteak
us.tinfoil
us.dghiaain
us.appeal3009drug
us.health-articles
us.sagittarius
us.banter
us.bizclientca-dp-momentousxmldomainnamewills
us.bigdartgun
us.adorn
us.alumina
us.defensive
us.corpsman
us.airmail
us.expulsion
us.1pr
us.aft5320pi11s
us.snowflake
us.hehndaks
us.natewilliams
us.alleviate
us.centric
us.phobic
us.preface
us.level-1
us.barge
us.bullhead
us.coronado
us.diffractometer
us.depositary
us.crass
us.cavern2fleabag
us.bittersweet
us.bigotry
us.citrus
us.gor
us.claus
us.drive
us.home-mortgage-rates
us.aleph
us.diehard
us.concubine
us.aoptpie
us.tuscarora
us.ion6702pi11
us.bludgeon
us.buoy
us.rodent
us.capitoline
us.confess
us.foul
us.hammerhead
us.netclientca-dp-momentousxmldomainnamewills
us.anorthic
us.botanic
us.syllabify
us.wexantsa
us.maternal
us.santiago
us.anhydrite
us.waftarmo
us.moratorium7221biz
us.indenting7325nx
us.sms2
us.addenda
us.statela
us.detention
us.crab
us.anort
us.ricochet
us.baritone
us.vest9780tabs
us.antramao
us.crawl
us.autotruck7158rx
us.crupper
us.option
us.julep
us.adapt
us.coauthor
us.gristmill
us.bumble3749pill
us.carpentry
us.tr2
us.argus
us.hypercube
us.egress
us.coriander
);


my $_version = "1.0.0";



################################################################################
#
MAIN:
#
################################################################################
{ 
     # Get the options
     Getopt::Long::Configure("bundling");

     my $options = Getopt::Long::GetOptions
       (
        "t|table=s"		=> \$opt_table,
        "w|wizard"		=> \$opt_wizard,
        "v|version"		=> \$opt_version,
		"x|xdebug"		=> \$opt_debug,
        "h|help"		=> \$opt_help
       );


	&StdHeader( "DomainMove" ) if ( ! $opt_wizard );		
				
    &Usage() if ( $opt_help );


	my $dbh = &ConnectServer() or die;
	&LoadCategories();

	my $counter = 0 + 0;

	foreach ( @domain_list )
		{	next if ( ! defined $_ );
			my $reverse_domain = $_;
			
			$dbh = &SqlErrorCheckHandle( $dbh );

			die if ( ! $dbh);
			die if ( $dbh->err );
	
			my $domain = &ReverseDomain( $reverse_domain  );

			next if ( length( $domain ) < 6 );

			my $retcode = &LookupUnknown( $domain, 0 );
			my ( $old_catnum, $source );

			if ( ! $retcode )
				{	print "Unknown $domain\n";
					$old_catnum = 0 + 55;
					&AddNewTrans( $domain, $old_catnum, 0, 3 );
				}
			else
				{	( $old_catnum, $source ) = &FindCategory( $domain, $retcode );
					$old_catnum = 0 + 55 if ( ! $old_catnum );
				}


			my $str = "UPDATE IpmContentDomain SET CategoryNumber = \'$old_catnum\', TransactionTime = getutcdate() WHERE DomainName like \'$reverse_domain.%\' AND CategoryNumber <> \'$old_catnum\'";
			my $sth = $dbh->prepare( $str );
			$sth->execute();
			
			my $rows = $sth->rows;
			$counter += $rows;

			print "Changed $rows for domain $domain\n";

			&SqlErrorHandler( $dbh );
			$sth->finish();
		}
		
	$dbh->disconnect if ( $dbh );
	
	print "Changed $counter rows total\n";

	&StdFooter if ( ! $opt_wizard );

exit;
}

exit;
################################################################################



################################################################################
#
sub TrapErrors()
#
#  Setup to Trap Errors
#
################################################################################
{	my $filename;
	my $dir = &SoftwareDirectory();

	$filename = $dir . "\\SqlTransferErrors.log";
	
	my $MYLOG;
   
	open( $MYLOG, ">$filename" ) or &lprint( "Unable to open $filename: $!\n" );       	   
	&CarpOut( $MYLOG );
   
	&lprint( "Set error logging set to SqlOptimizeErrors.log\n" ); 
}



################################################################################
# 
sub Usage
#
################################################################################
{
    my $me = "SqlSourceNumber";

    bprint <<".";
Usage: $me
There are no command line arguments.

 
.
    &StdFooter;

exit;
}




################################################################################
# 
sub Version
#
################################################################################
{
    my $me = "SqlTransfer";

    bprint <<".";
$me $_version
.
    &StdFooter;

    exit;
}



__END__

:endofperl
